# Generated by Django 5.2.14 on 2026-05-12 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrippingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criteria_type', models.CharField(choices=[('time', 'Time After Enrollment (days)'), ('completion', 'Previous Lesson Completion'), ('quiz_score', 'Quiz Score Threshold'), ('manual', 'Manual Admin Unlock'), ('purchase_tier', 'Course Tier Purchase')], max_length=20)),
                ('unlock_after_days', models.PositiveIntegerField(blank=True, help_text='Days after enrollment to unlock', null=True)),
                ('required_score', models.PositiveIntegerField(blank=True, help_text='Minimum quiz score percentage (0-100) to unlock', null=True)),
                ('is_globally_locked', models.BooleanField(default=False, help_text='Lock for all, admin unlocks individually')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drip_rule', to='courses.lesson')),
                ('required_lesson', models.ForeignKey(blank=True, help_text='Lesson that must be completed first', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks_lessons', to='courses.lesson')),
                ('required_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gates_lessons', to='assessments.moodlequiz')),
            ],
        ),
        migrations.CreateModel(
            name='ContentAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_reason', models.CharField(blank=True, max_length=100)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_access', to='courses.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='courses.lesson')),
            ],
            options={
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
