# Generated by Django 5.2.14 on 2026-05-13 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('dripping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drippingrule',
            name='required_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gates_lessons', to='assessments.quiz'),
        ),
    ]
