# Generated by Django 5.2.14 on 2026-05-12 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('html', 'HTML Block'), ('video', 'Video'), ('h5p', 'H5P (Moodle)'), ('document', 'Document / PDF'), ('image', 'Image')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('html_content', models.TextField(blank=True, help_text='Raw HTML content')),
                ('is_fullscreen', models.BooleanField(default=False, help_text='Render HTML block fullscreen')),
                ('file', models.FileField(blank=True, null=True, upload_to='content_files/')),
                ('h5p_embed_url', models.URLField(blank=True, help_text='Moodle H5P embed.php URL')),
                ('moodle_resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube / Vimeo embed URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
