# Generated by Django 5.2.14 on 2026-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='h5p_extracted_path',
            field=models.CharField(blank=True, help_text='Path to extracted H5P content', max_length=255),
        ),
    ]
