# Generated by Django 5.2.14 on 2026-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blanks', 'Fill in the Blanks'), ('drag_drop_word', 'Drag and Drop Word')], max_length=20),
        ),
    ]
