# Generated by Django 5.2.14 on 2026-05-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blanks', 'Fill in the Blanks'), ('keyword_match', 'Keyword Match'), ('calculated_mcq', 'Calculated Multichoice'), ('drag_drop_word', 'Drag and Drop Word'), ('drag_drop_image', 'Drag and Drop Image')], max_length=30),
        ),
    ]
