# Generated by Django 5.2.14 on 2026-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='rendered_questions',
            field=models.JSONField(default=dict, help_text='Maps question UUID -> {prompt, variables, ...}. Populated on quiz start.'),
        ),
    ]
